server:
  port: 9000

spring:
  application:
    name: authorization-service
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      uri: mongodb://localhost:27017/authorization
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
