
server:
  port: 8082

spring:
  application:
    name: department-service
  sleuth:
    sampler:
      probability: 1.0
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/department
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka