spring.application.name=employee-service
spring.data.mongodb.uri=mongodb://localhost:27017/employee

server:
  port: 8085

spring:
  application:
    name: employee-service
  sleuth:
    sampler:
      probability: 1.0
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/employee
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

