server:
  port: 8080

spring:
  application:
    name: gateway-proxy

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

zuul:
  prefix: /api
  ignoredServices: '*'
  #####
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Access-Control-Expose-Headers, Access-Control-Allow-Methods
  ignore-security-headers: true
  default-filters: TokenRelay
  #####
  routes:
    employee-service:
      path: /employees/**
      stripPrefix: false
    department-service:
      path: /departments/**
      stripPrefix: false
    organization-service:
      path: /organizations/**
      stripPrefix: false

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
